version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
      - MYSQL_DATABASE=flask_db
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
